language: objective-c
os: osx
osx_image: xcode10.1
env:
  - USE_BAZEL_VERSION=last_green
before_install:
  - brew update >/dev/null
script:
  - |
    for f in $( ls ./Formula/*.rb ); do
      brew audit $f
      brew install -v $f
      brew test $f
      brew uninstall $f
    done
